# Generated by Django 3.2 on 2023-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('descricao_produto', models.CharField(blank=True, max_length=200, null=True)),
                ('preco_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('img_produto', models.FileField(blank=True, upload_to='produtos.images/')),
                ('status_produto', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default=0, max_length=10)),
            ],
        ),
    ]
